### ISSUE TITLE
VS Code section

### ISSUE THREAD

**Issue by yousefelgoharyx** [OsamaElzero/Frontend-Tools#8]
### **Editors**: VS Code

**Extensions**:

- [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify)

- [IntelliSense for CSS class names in HTML](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion)

- [live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)

- [npm Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense)

- [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)

- [Polacode](https://marketplace.visualstudio.com/items?itemName=pnp.polacode)

- [sass](https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented)

- [live sass compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass)

**presonalization**:

- [one dark pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme)

- [material icon theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)

**Comment by OsamaElzero** [comment]
Send Pull Request Please
